server:
  port: 8081
resilience4j:
  circuitbreaker:
    instances:
      sendTransaction:
        sliding-window-type: count_based
        sliding-window-size: 5
        failure-rate-threshold: 40
        wait-duration-in-open-state: 5s
